--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/SchdowNVIDIA/EC-TableUI bump.
branches:
- master
projects:
  EC-TableUI:
    path: ""
    libs:
    - src: PoggitTestPlugins/FormAPI/libFormAPI
      version: ^1.3
...
